### ISSUE TITLE
compatibility with scipy version < 0.14

### ISSUE THREAD

**Issue by EasyIsrael** [lmfit/lmfit-py#182] opened 2015-01-02 10:46 UTC
Hi,

i tried this lib with scipy version 0.13.3. Due to the docs it should work, but there is an import of a class  in the file "_differentialevolution.py" that is added in ver. 0.14. (OptimizeResult)
with the folowing changes it works for me:
change line 7 in _differentialevolution.py:
from: 
[7]  from scipy.optimize import OptimizeResult, minimize
to: 
[7]   import scipy
[8]   if scipy.__version__ >= "0.14.0":  from scipy.optimize import OptimizeResult
[9]   from scipy.optimize import minimize

**Comment by andyfaff** [comment] 2015-01-02 11:04
This should be fixed by #180

**Comment by tritemio** [comment] 2015-01-02 18:32
This is also a duplicate of #177 and can be closed.

**Comment by newville** [comment] 2015-01-05 00:20
fixed with 956f29c6df462bcc80529671cece8f49598b9b69

**Closed by newville** 2015-01-05 00:20 UTC
