### ISSUE TITLE
Model.plot() problem when Model.name contains underscore and matplotlib configured to render text using TeX

### ISSUE THREAD

**Issue by gparadis** [lmfit/lmfit-py#373] opened 2016-09-26 01:09 UTC
Using latest version (0.9.5). Default value of `Model.name` is `Model(funcname)`, where `funcname` is the name of the Python function passed as the `func` argument of the `Model` object constructor. It is very common for Python function names  to contain the underscore character. `Model.plot()` generates TeX errors if `matplotlib` is configured to  use TeX to render text.

The problem is that TeX chokes on underscores unless they are either contained in a math environment (not the case here) or escaped with backslash. I am sure that I am not the only Jupyter-Notebook-addict user out there to use `lmfit` to do some fancy non-linear distribution fitting _and_ using TeX to render figures that use the oh-so-pretty Computer Modern LaTeX font (to match the text in the body of the math-laden manuscripts I am preparing for submission to peer-reviewed journals).

This can easily be patched by escaping underscores in `Model.name` if `rcParams['text.usetex']` exists and evaluates to `True`. Here is the code I use to patch the situation in my notebook. It would be fairly simple to implement something similar inside `Model.plot()`.

```
from matplotlib import rc, rcParams
if 'text.usetex' in rcParams and rcParams['text.usetex']:
    m.name = m.name.replace('_', '\_')
```

The original value of `Model.name` could be saved in a local variable and restored before returning from `Model.plot()`, if you want to avoid silently modifying the `Model` instance (probably best, assuming POLA policy).

**Comment by newville** [comment] 2016-09-26 12:50
@gparadis   Normally, I'm not too excited about changing the `Model.fit_xxxx()` functions -- they are meant to be quick-and-dirty plots.   But, it does look like this will prevent plots from being created in some situations, and so should be fixed. 

I think the approach of testing whether `rcParams['text.usetex']` has been set is fine.   But, just to throw it out there, another completely viable alternative would be to force `rcParams['text.usetex']=False`.   That is, `lmfit.Model.fit_xxxx()` produces simple plots of model and fit (and maybe residual and initial mode), but we never really promised *how* that happens or that we're going to follow any specific stylistic choices.    I'm not *opposed* to trying to follow what the end-user has set up in their `matplotlib.rcParams`, but I think we don't want to guarantee that we will.

**Comment by gparadis** [comment] 2016-09-26 21:56
@newville You could force `rcParams['text.usetex'] = False`, but would have to restore the state back to `True` before returning from the function (sneaky side-effects on relatively obscure environment parameters that the user took the time to set is not cool). Temporarily disabling and restoring TeX rendering would be about as much work to implement as temporarily escaping and restoring the backslash in the title string. In the escaped backslash route, the user magically gets what they wanted in the first place. In the disabled TeX rendering route, the user gets to wonder why TeX rendering is not working here, but works everywhere else in their notebook. The POLA points to the escaped backslash route.

**Comment by newville** [comment] 2016-09-26 22:46
@gparadis  Well, matplotlib + IPython use magic global state variables all over the place.  
"Sneaky side effects" is actually a pretty good description of  IPython in general.    If you're using matplotlib and IPython together, you are going to be on the receiving end of much magic.   It seems this is something desirable to you. ;).

OK, you've used POLA twice now.  To me, invoking the principle of least surprise is indistinguishable from "the behavior I want".    One might interpret consistency as implying that lmfit should produce the same plot for every user who runs the same code.  That would argue in favor of ignoring any and all rcParams settings.  Again, I do not have a strong opinion on this.  But "what I want for my IPython session right now" is not really a very compelling argument to me. 

Adding tests for various optional settings of `rcParams` could easily become a real headache.   Again, I'm not saying we shouldn't do this, but I'm not at all excited about it.

**Comment by gparadis** [comment] 2016-09-26 23:38
@newville You could just leave things exactly the way they are, if you think that is best to let the user handle the unescaped-backslash+TeX case. Anyone using `rcParams['text.usetex'] = True` should expect `matplotlib` to barf eventually. ;)

I my experience, the POLA is a useful concept when I am making design decisions. Your mileage may vary. My comments are based on the assumption that my situation was not unique, i.e. `lmfit` users are looking to do some sort of "fancy" distribution fitting (beyond what they can do in two or three lines of code with `scipy.optimize.curve_fit`) _and_ working in a research context requiring publication of math-intensive papers (hence `rcParams['text.usetex'] = True`). I will readily admit that this is pure conjecture on my part, but it seemed plausible to me so I posted an issue. My motivation for taking the time to post an issue was in the spirit of service to the community, rather than to try to induce convenient-for-me change to the code base. I already got "the behaviour I want" by monkey-patching the `Model` class at runtime. If the use case I describe is in fact an obscure corner case, then I agree that it is a bad idea to handle it in the `lmfit` code.

**Comment by andyfaff** [comment] 2016-09-26 23:40
Are there any model names in lmfit that currently start with an underscore? If not, then I'd argue it's up to the user not to use model names with an underscore as a prefix.

**Comment by gparadis** [comment] 2016-09-27 00:04
@andyfaff The first argument of the `Model` class constructor (`func`) corresponds to the user-defined function, to which the user want to fit to observed data. This sets `self.func` in `Model.__init__`.

The `Model.name` property returns `self._reprstring()`, which returns `'Model(%s)' % self._name`, where `self._name` is (by default) set to `self.func.__name__` in `Model.__init__`. It is common to have backslashes in Python function names, so it will be equally common for `Model.name` to contain backslashes.

**Comment by newville** [comment] 2016-09-27 00:41
@andyfaff None of the builtin models currently start with an underscore, but some of the model function names do contain underscores (`students_t` for example).  I think the problem is that any underscore in a text string will break  matplotlib's text rendering if `rcParams['text.usetex'] = True`, and that function names are rendered as text strings.   Similar problems could arise if there were underscores in the name of the independent variable, too.

Using `rcParams['text.usetex']` everywhere instead of explicitly using dollar signs for any part of a string that should be typeset with latex certainly seems like it is asking for trouble to me.   But, since it is `Model.plot_*()` that is causing exceptions to be raised, it is a perfectly reasonable question of how to best handle this case when 

@gparadis  POLA begs the questions of who it is that one is trying to astonish the least.  If you can provide the objective function to define "astonishment", we might be be able to help ;).   Anyway, it's certainly not the only aspect of API design.   We're just trying to do the best we can. 

But just because a user sets a global matplotlib parameter doesn't imply that `Model.plot_*()` needs to obey that setting.

**Comment by gparadis** [comment] 2016-09-27 01:09
I agree that `lmfit` code does not _need_ to account for all possible combinations of global `matplotlib` settings. That is why I agreed earlier that maintaining _status quo_ is a reasonable option. My suggestion to catch the unescaped-underscore + `rcParams['text.usetex']` case maintains current function behaviour for all other cases. As such, it will either reduce or have a null effect on individual user astonishment, depending on the case. Assuming a non-zero probability of the problematic case occurring and an objective function that minimizes the weighted sum of individual user astonishment (with a non-negativity constraint on weight coefficients), the proposed change will always have a net positive effect on the objective function. ;)

@newville I have no doubt that you are doing the best you can. `lmfit` is a great project. My bothering to use it and providing constructive suggestions to improve user experience is testimony to this. Thanks for making the world a better place for all the distribution-fitting nerds out there!

**Comment by newville** [comment] 2016-09-30 03:45
The further we get from this issue being raised, the more I feel that the best solution is to document the potential problem and not make any changes to the code.  That is, setting `rcParams['text.usetex'] = True` (meaning "send all strings through latex") seems like a really bad idea, and I don't think we want to encourage it or go out of our way to handle it.   

PRs for changes to the docs  would be most welcome.

**Closed** 2017-01-14 14:21 UTC
