### ISSUE TITLE
Test suite failure

### ISSUE THREAD

**Issue by tillea** [lmfit/lmfit-py#502] opened 2018-10-04 10:06 UTC
Hi,
there is a bug report for Debian about a [failure of the build time test](https://bugs.debian.org/906381).
The bug was reported against version 0.9.7 but I also had no success to build version 0.9.11.

Version information

    Python: 2.7.15+ (default, Aug 31 2018, 11:56:52) 
    [GCC 8.2.0]
    scipy: 1.1.0, numpy: 1.14.5, asteval: 0.9.12, uncertainties: 2.4.4, six: 1.11.0

    Python: 3.6.7rc1 (default, Sep 27 2018, 09:51:25) 
    [GCC 8.2.0]
    scipy: 1.1.0, numpy: 1.14.5, asteval: 0.9.12, uncertainties: 2.4.4, six: 1.11.0

Kind regards, Andreas.

**Comment by reneeotten** [comment] 2018-10-04 11:51
we've seen this test failure as well at some point in March with a newer versions of scipy (I think scipy 1.0.1), but that should have been fixed by #467 (so in all versions after 0.9.10). For me (and Travis) the test-suite seems to pass, so I am not sure... The report is for 0.9.7 but you say that 0.9.11 doesn't work either, can you please post the full log (i.e., is it the same failure)?

**Comment by newville** [comment] 2018-10-04 15:29
@tillea @reneeotten  Hm, I don't see where those errors are really coming from.  It sort of looks like they are coming from `scipy.optimize` -- that's not to blame them and say "it is not our problem", just trying to identifying where the problem is.  

But, I don't get those errors with scipy 1.1.0.   So, I'm not sure.   We do test regularly with Travis, and so miniconda.   In general, it's hard for us to support every packaging system, even ones as obviously useful as debian.   That's not to say we cannot help, but we'll need more to go on to try to help you solve this issue.  Like Renee asked, can you post the results?    Of course, we're most interested in failures from the latest release and github master branch.

**Comment by tillea** [comment] 2018-10-05 08:34
Hi,
thanks for both very quick responses.  I'll come up with more details about the current issue soon but probably I will not manage before beginning of next week.
Kind regards, Andreas.

**Comment by reneeotten** [comment] 2018-10-10 11:00
@tillea yes it does ;) It's caused by the ```uncertainties``` package and looking at it your first post again I realize now that you're not installing the correct dependencies. As listed in the ```requirements.txt``` you should have at least these packages and version numbers:
```
six>1.10
numpy>=1.10
scipy>=0.17
asteval>=0.9.12
uncertainties>=3.0
```

so both ```scipy``` and ```uncertainties``` are too old - can you update those and try again?

**Comment by tillea** [comment] 2018-10-11 09:15
> @tillea It is also not very encouraging to see the wrong version for uncertainties twice. Isn't getting the dependencies right the whole point of packaging?
Yes, one a package is released the dependencies should be right.  As long as it can not be build (for whatever reason) you see sometimes things that are not right.

> It's also strange to see 'lmfit-py-0.9.11+dfsg' in the error messages. Making packages for debian any package manager from anything except "official release version" seems like a very bad idea to me. Perhaps you can explain why you want to do that?
Its not **me** who **wants** to do **that**.  I'm just trying to fix an issue that is not dealt with by the official Uploader of the package (I have no idea why Frédéric (in CC) excluded three files which is documented inside the [debian/copyright](https://salsa.debian.org/science-team/lmfit-py/blob/master/debian/copyright) file.  The fact that files were removed is flagged by the _+dfsg_ appendix.  Since all excluded files belong to the docs (I guess the according Debian packaged sphinx doc is used) I do not see any reason for the observed issues.
I hope this explains what you was asking for, Andreas.

**Comment by picca** [comment] 2018-10-11 11:03
Hello, I just removed these files:
```
doc/sphinx/apigen.py doc/sphinx/github.py doc/sphinx/numpydoc
```
numpy doc is already available as a package, github was not used, if I am not wrong and for apigen.py I do not remember.

I do not take care of this because, I am also waiting for the `uncertainties` to be accepted by Debian.
thanks Andrea for this packaging

**Comment by tillea** [comment] 2018-10-11 13:53
> That error is actually not coming from `lmfit`, but is thrown by the `uncertainties` package. I can confirm that this error happens when you use install uncertainties from the `master` GitHub branch, which is an unreleased version. If you install the released 3.0.2 version (https://github.com/lebigot/uncertainties/releases/latest) that problem isn't there. I suppose that for Debian you'd stay with released version only anyway, so I guess you packaged the "wrong" version this time.

We are definitely using released versions ans in the python-uncertainties case we used the [from pypi](https://pypi.org/project/uncertainties/#files) that is usually considered a trustworthy source.  Unfortunately this tarball with the same name as can be downloaded from [Github](https://github.com/lebigot/uncertainties/releases/latest) has different size and content of files.
So I  tried the version from Github but in the end I keep on getting the

    ERROR: Failure: TypeError (ord() expected a character, but string of length 3 found)

errors.  So unfortunately I can not report any enhancement even with the Github code.
Any other idea?
Kind regards, Andreas.

**Comment by newville** [comment] 2018-10-11 14:55
@tillea @picca  I just verified that all of the lmfit tests pass for me with uncertainties 3.0.2 as installed with `pip install uncertainties` and lmfit 0.9.11 for Python 2.7.15 and Python 3.6.6.  

I do not know what you are doing wrong with your build, but then again you haven't told us what you are actually doing.  In fact, you've not included what commands you run to generate whatever errors you get.    The reports you have given are not at all encouraging.   Please use only released code, not code from github, get the dependencies right, and do not remove files or change version numbers.   It's slightly alarming that I have to tell you this.

Please explain exactly what you are doing to build a debian package, including why you are not doing `pip install lmfit`.   

We can and do support `pip install` and `conda install` without much trouble, so if a debian package is challenging to create or maintain, it may not be worth the effort. 

I do not see any evidence of problems with lmfit here.

**Comment by reneeotten** [comment] 2018-10-11 16:05
As I said yesterday, I did get the same error as you reported at some point - now I have difficulties reproducing it. Having said that, it's something in the packaging of the ```uncertainties``` package - after building that, did you run their test-suite? Or just open Python and do the ```import uncertainties``` statement, that should already trigger the error, if present. If that passes, there is no reason why lmft wouldn't like it... I am not sure what the issue is, but as Matt said explaining the exact steps in the build process might shed some light.

**Comment by tillea** [comment] 2018-10-14 06:17
Hi Renee,
On Thu, Oct 11, 2018 at 09:05:25AM -0700, Renee Otten wrote:
> As I said yesterday, I did get the same error as you reported at some point - now I have difficulties reproducing it. Having said that, it's something in the packaging of the ```uncertainties``` package - after building that, did you run their test-suite? Or just open Python and do the ```import uncertainties``` statement, that should already trigger the error, if present. If that passes, there is no reason why lmft wouldn't like it... I am not sure what the issue is, but as Matt said explaining the exact steps in the build process might shed some light.
I was able to solve the issue with uncertainties.  Please feel free to close this issue.
Kind regards, Andreas.

**Comment by newville** [comment] 2018-10-14 14:39
@tillea OK, we can close this.  Out of curiosity, would you be willing to summarize the problem and solution?  I'm not sure I ever fully understood what was going wrong.  It seemed to start out being about `scipy`, but then was about `uncertainties` versions.  It seems it might have been something that might have been seen elsewhere, but was sort of hard to reproduce reliably (I think...).   

As it stands,  I'm not sure if there is a problem we should know about.

**Comment by newville** [comment] 2018-10-22 23:57
OK, I guess we'll close this.

**Closed by newville** 2018-10-22 23:57 UTC
