### ISSUE TITLE
Python crash when fixing the parameter to itself.

### ISSUE THREAD

**Issue by vkoroteev** [lmfit/lmfit-py#483] opened 2018-06-19 09:55 UTC
Python crashes when you accidentally set fit parameter expression to the name of the parameter.

###### Version information
Python: 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
lmfit: 0.9.10, scipy: 1.1.0, numpy: 1.14.2, asteval: 0.9.12, uncertainties: 3.0.2, six: 1.11.0

###### A Minimal, Complete, and Verifiable example
from lmfit.models import LinearModel
x = [x for x in range(10)]
y = [e*10 for e in x]
mod = LinearModel()
mod.set_param_hint('slope', expr = 'slope')
out = mod.fit(y, x=x)

I have python crash on the last line.

**Comment by newville** [comment] 2018-06-20 03:28
Hm, I don't get crash on either macOS and Linux.  I get a RecursionError, which seems sensible enough to me.  I'll try on Windows 64-bit soon, but will be very surprised if that crashed the interpreter on Windows.  The code involved for this is pure Python, so that would be a Python bug.

**Comment by newville** [comment] 2018-06-20 18:12
@vkoroteev As I suspected, I don't get a crash on 64 bit Windows either, using the same Anaconda Python version (3.6.5) as you.  I get a RecursionError on all systems I tried.

In short, I cannot reproduce the problem reported and am skeptical that we will have uncovered a bug in Python which causes crashes where one would expect a RecursionError or some other runtime exception.

**Comment by vkoroteev** [comment] 2018-06-21 08:50
It sounds like good news. Seems this is not a bug in lmfit, but my personal installation issue.

**Comment by newville** [comment] 2018-06-21 14:38
@vkoroteev can you verify that you really get Python to crash, and not give an exception with your example?

**Comment by vkoroteev** [comment] 2018-06-21 16:20
I believe this is crash.
![crash](https://user-images.githubusercontent.com/7648791/41731800-9e039512-757f-11e8-8da0-5ee0b7d3fd4e.png)

Here is complete Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	3.6.5150.1013
  Application Timestamp:	5abd3210
  Fault Module Name:	python36.dll
  Fault Module Version:	3.6.5150.1013
  Fault Module Timestamp:	5abd3161
  Exception Code:	c00000fd
  Exception Offset:	000000000003b486
  OS Version:	6.3.9600.2.0.0.256.4
  Locale ID:	2057
  Additional Information 1:	3904
  Additional Information 2:	39044e702727b94b27e6870670013fa6
  Additional Information 3:	303d
  Additional Information 4:	303ddaf677cfafd6782f2fc809530fbc

**Comment by newville** [comment] 2018-06-22 01:13
@vkoroteev Sounds like a Jupyter bug to me.  I'll close this, but if you think this really is a lmfit issue, feel free to re-open it.

**Closed by newville** 2018-06-22 01:13 UTC
