### ISSUE TITLE
issue with least_squares method and parameter expression or fixed parameters

### ISSUE THREAD

**Issue by reneeotten** [lmfit/lmfit-py#416] opened 2017-05-16 00:53 UTC
opening an issue after starting the discussion on the [mailing list](https://groups.google.com/forum/#!topic/lmfit-py/eJH73ZARV-E).

There seems to be an issue when using the `least_squares` method and having parameters fixed or constrained with an expression. The calculation of `nvarys` and other fitting statistics (`redchi`, `aic` and `bic`) do not take into account whether or not a parameter is varied. In addition, when using parameter expressions fits do not converge to the correct answer as far as I can tell (see example on the mailing list). The test that was included when the `least_squares` method when adding the method only tests one scenario where all fitting parameters are varied. 

I am opening this issue to investigate it further and hopefully get some insight from others (for example from @Tillsten who added the method).

**Comment by newville** [comment] 2017-05-16 02:30
@reneeotten   Thanks as always.  I think we were just kind of lax in adding support for `least_squares`.   I might suggest we actually have a conversation about what parts of `least_squares` should be supported, and how closely lmfit should follow `scipy.optimize` simply because they made a bunch of unpleasant API choices.  

Honestly, I don't think that `least_squares` with `method='lm'` adds that much useful, and I would suggest that we should simply not support it.   For clarity, `least_squares` advertises that it supports bounds and non-least-squares cost functions.  But with `method='lm'`, it does neither.   Even with that caveat, the reasons to use `least_squares` is for one of two cases:

1. problems with "large sparse jacobians".  Serious, non-rhetorical question: can someone explain how a lmfit user or even a scipy user is going to know if their problem  is "large and sparse" or has a "rank deficient jacobian"?

2. in order to use a loss function other that what is somewhat confusingly called "linear" (this of course, does not imply the problem is linear in the parameter space).   But, if you do use a loss function other than "linear", `scipy.optimize.least_squares` is actually not solving a problem by least squares. 

Ugh.  Sorry, I know that sounds really ranty.  I do think that support for "trust region reflective" (which they unfortunately abbreviate "trf") is an OK idea -- marginally better than not supporting `least_squares` at all.

**Comment by Tillsten** [comment] 2017-05-16 18:20
Just two points
LM is also trust region algorithm, trf could be seen as the evolution of it (http://www.applied-mathematics.net/LMvsTR/LMvsTR.pdf). I think you are too hang about the interface of the function, i think it is quite ok, but as you point out it is not perfect. Pro point for 'least_squares', including 'lm' mode : It performs much better than 'leastsq' for my problems.  In fact, if i had time, which i don't,  and if it wouldn't break backwards compatibility, i would even argue to make it the default minimizer.

**Comment by newville** [comment] 2017-05-16 18:48
@Tillsten   Thanks -- I agree that the complaints I expressed are slightly ranty, and that there is good code in `least_squares`.  But, I still get a headache every time I think about to wrap `least_squares` with all its permutations of interdependent options ;).  I also agree that LM is a trust-region method, just somewhat more conservative in it step size.

But, I believe that `least_squares(..., method='lm', ...)` calls exactly the same MINPACK.lmdif that `leastsq()` calls.  Perhaps some of the options (tolerances etc) are slightly different.  I haven't looked in detail, but I'm not sure why it should perform differently.

**Comment by Tillsten** [comment] 2017-05-16 18:58
@newville Oh, i was wrong, i misread the docstring and checked, all my tested problems used bounce, hence the trf version. Sorry for that confusion.

**Comment by reneeotten** [comment] 2017-05-16 23:59
@Tillsten thank you for your comments! I agree that `least_squares` could have some benefits and had no intentions of dismissing it as not useful. I was just trying out all different fitting algorithms supported by lmfit for my minimization problem and noticed that `least_squares` didn't converge to the same values. 

After a bit of trial-and-error it _seems_ to me that this could be related to parameters with expressions defined. Do you have parameter expressions and/or fixed parameters in your typical use-case, or are all of them varied? I would like to make sure that there is an issue with the implementation of the `least_squares` method in lmfit and not something trivial I am doing wrong...

That being said, we could/should probably improve the support for `least_squares` a bit and at least make sure that the options user can pick do actually work as intended.

**Comment by newville** [comment] 2017-05-17 14:26
@reneeotten @Tillsten  I think the current `lmfit.minimizer.least_squares` just isn't preparing the fit correctly, including identifying the parameters that are really variables.    That shouldn't be too hard to fix.

But: I think that we should decide how much of `scipy.optimize.least_squares` to support in `lmfit`.  I think there's no need for it's `method='lm'`, but I'm not 100% sure of that....  One approach might be to support *only* `method='trf'`, and then call it `lmfit.minimizer.trf`.  

We have (IMHO) a better way to specify bounds, and should use that instead of the approach taken by `least_squares`.  And, we sort of have a mechanism for modified cost functions -- we could use/expand that rather than rely on what `least_squares` does.

**Comment by newville** [comment] 2017-05-31 19:22
@reneeotten  The issue of incorrectly counting the number of actual variables is fixed with 0.9.7rc2.  To try to address the other issue of fits not converging well when using constraints,  I changed `least_squares()` to better create the array of true variables and their bounds.  These now do not count fixed or constrained parameters as variables, but still update constraints for the call to the residual function.   I think this should work better, and it seems to work OK for me in simple tests.  Would you try again with your previously failing example?

.I do see that the number of function evaluations is wrong. It looks to be counting number of fitting loops (so, low by roughly a factor of Nvary).  I don't consider this a big deal, and probably counts as an upstream bug.  Also, `least_squares` does not return any information for calculating uncertainties.  At this point, I think we have to take these as "features".

**Comment by reneeotten** [comment] 2017-06-01 02:31
@newville that looks great!! My previously failing examples work perfectly now and converge to the same values as when using the `leastsq` (or any other) method.

The number of function evaluations indeed seems a bit low, but that perhaps has to do with the fact the for `least_squares` it only counts the times `__residual` is called, while for the other methods it seems to me it also includes the calls to `__jacobian` (at least as far as I can tell). The `least_squares` method in SciPy does return `nfev` and `njev` for function and jacobian evaluations, respectively. I haven't tried yet, but perhaps taking the sum of these two will yield a result that's more comparable to what the other methods in `lmfit` report? But I agree this is a very minor issue anyway... 

The fact that it doesn't return information to calculate uncertainties is slightly more annoying, but from reading #369 this would be possible to solve. But right now uncertainties are only reported for `leastsq` and none of the other methods, so this doesn't seem like an issue that would block a new release - or..?

**Comment by newville** [comment] 2017-06-01 11:53
@reneeotten Great!  Let's call the current `least_squares` in lmfit "not broken" and be satisfied with that for the time being (and 0.9.7).    

I believe the other issues are really upstream issues for `scipy.optimize.least_squares` anyway.

**Closed** 2017-06-03 13:11 UTC
