### ISSUE TITLE
model.make_params is ignoring `vary` when settings parameters

### ISSUE THREAD

**Issue by KedoKudo** [lmfit/lmfit-py#971] opened 2024-10-14 15:37 UTC
### DO NOT IGNORE ###

READ THESE INSTRUCTIONS FULLY. IF YOU DO NOT, YOUR ISSUE WILL BE CLOSED.

If you have not submitted a GitHub Issue to lmfit before, read [this](https://github.com/lmfit/lmfit-py/blob/master/.github/CONTRIBUTING.md) first.

***DO NOT USE GitHub Issues for questions, it is only for bugs in the lmfit code!***

Issues here are concerned with errors or problems in the lmfit code.  We use it as our bug
tracker.  There are other places to get support and help with using lmfit.

If you **think** something is an Issue, it probably is not an Issue. If the behavior you
want to report involves a fit that runs to completion without raising an exception but
that gives a result that you think is incorrect, that is almost certainly not an Issue.

Use the [mailing list](https://groups.google.com/group/lmfit-py) or [GitHub discussions
page](https://github.com/lmfit/lmfit-py/discussions) for questions about lmfit or things
you think might be problems.  We don't feel obligated to spend our free time helping
people who do not respect our chosen work processes, so if you ignore this advice and post
a question as a GitHub Issue anyway, it is quite likely that your Issue will be closed and
not answered. If you have any doubt at all, do NOT submit an Issue.

To submit an Issue, you MUST provide ALL of the following information.  If you delete any
of these sections, your Issue may be closed. If you think one of the sections does not
apply to your Issue, state that explicitly. We will probably disagree with you and insist
that you provide that information. If we have to ask for it twice, we will expect it to be
correct and prompt.

#### First Time Issue Code

Yes, I read the instructions and I am sure this is a GitHub Issue.

#### Description

The method `model.make_params` is ignoring the `vary` argument when batch creating parameters.
This is a confusing behavior as users would generally assume `make_params` is a simple way to batch define input parameters for a fitting functions, but the expected behavior is different with setting each one individually.

###### A Minimal, Complete, and Verifiable example

- Here is a simple linear function to fit where `a0` and `b0` are calculated from a separate routine, thus should be fixed during the subsequent fitting.

```python
def kropff_low_lambda_attenuation(
    lda: np.ndarray, a0: float, b0: float, ahkl: float, bhkl: float
) -> np.ndarray:
    return a0 + b0 * lda + ahkl + bhkl * lda
```

- Let's create simple example data

```python
# Create synthetic data
lda = np.linspace(1, 5, 100)
a0_true = 0.5
b0_true = 0.3
ahkl_true = 0.9
bhkl_true = 0.1

attenuation = kropff_low_lambda_attenuation(lda, a0_true, b0_true, ahkl_true, bhkl_true)
```

- Now let's create the model, then the parameters with `model.make_params`

```python
model = Model(kropff_low_lambda_attenuation, independent_vars=["lda"])
params = model.make_params(
    a0=Parameter("a0", value=0.5, vary=False),  # user expects a0 to be fixed during fitting
    b0=Parameter("b0", value=0.3, vary=False),  # user expects b0 to be fixed during fitting
    ahkl=Parameter("ahkl", value=0.8, vary=True),  # user expects ahkl to be fitted
    bhkl=Parameter("bhkl", value=0.2, vary=True),  # user expects bhkl to be fitted
)
```

- Time to fit (see output in the next section), and `lmfit` is fitting all four parameters and ignoring the `vary` setting

```python
result_incorrect = model.fit(attenuation, params, lda=lda)
print(result_incorrect.fit_report())
```

- If we define each parameter without using `make_params`, `lmfit` is functioning as expected (report in next section).

```python
model = Model(kropff_low_lambda_attenuation, independent_vars=["lda"])
result = model.fit(
    attenuation,
    lda=lda,
    a0=Parameter("a0", value=0.5, vary=False),
    b0=Parameter("b0", value=0.3, vary=False),
    ahkl=Parameter("ahkl", value=0.8, vary=True),
    bhkl=Parameter("bhkl", value=0.2, vary=True),
)
print(result.fit_report())
```

###### Fit report:

- Incorrect fitting when using `make_params`
```bash
[[Model]]
    Model(kropff_low_lambda_attenuation)
[[Fit Statistics]]
    # fitting method   = leastsq
    # function evals   = 23
    # data points      = 100
    # variables        = 4
    chi-square         = 4.8811e-30
    reduced chi-square = 5.0845e-32
    Akaike info crit   = -7201.73571
    Bayesian info crit = -7191.31503
    R-squared          = 1.00000000
[[Variables]]
    a0:    0.51781749 +/- 4.8035e-07 (0.00%) (init = 0.5)
    b0:    0.24061497 +/- 1.6943e-07 (0.00%) (init = 0.3)
    ahkl:  0.88218251 +/- 4.8035e-07 (0.00%) (init = 0.8)
    bhkl:  0.15938503 +/- 1.6943e-07 (0.00%) (init = 0.2)
[[Correlations]] (unreported correlations are < 0.100)
    C(b0, bhkl) = -1.0000
    C(a0, ahkl) = -1.0000
```

- Correct fitting results when not using `make_params`

```bash
[[Model]]
    Model(kropff_low_lambda_attenuation)
[[Fit Statistics]]
    # fitting method   = leastsq
    # function evals   = 7
    # data points      = 100
    # variables        = 2
    chi-square         = 6.3109e-30
    reduced chi-square = 6.4397e-32
    Akaike info crit   = -7180.04467
    Bayesian info crit = -7174.83433
    R-squared          = 1.00000000
[[Variables]]
    a0:    0.5 (fixed)
    b0:    0.3 (fixed)
    ahkl:  0.90000000 +/- 7.0033e-17 (0.00%) (init = 0.8)
    bhkl:  0.10000000 +/- 2.1758e-17 (0.00%) (init = 0.2)
[[Correlations]] (unreported correlations are < 0.100)
    C(ahkl, bhkl) = -0.9320
```

###### Error message:

N/A

###### Version information

```
Python: 3.11.10 | packaged by conda-forge | (main, Sep 10 2024, 10:57:35) [Clang 17.0.6 ]

lmfit: 1.3.2, scipy: 1.14.1, numpy: 2.1.1,asteval: 1.0.4, uncertainties: 3.2.2
```

**Comment by newville** [comment] 2024-10-14 18:06
The usage for `Model.make_params()`  (see https://lmfit.github.io/lmfit-py/model.html#lmfit.model.Model.make_params)

would be

```
model = Model(kropff_low_lambda_attenuation, independent_vars=["lda"])
params = model.make_params(
    a0=dict(value=0.5, vary=False), 
    b0=dict(value=0.3, vary=False),  
    ahkl=dict(value=0.8, vary=True),  
    bhkl=dict(value=0.2, vary=True),  
)
```


Usage like
```
params = model.make_params(
    a0=Parameter('a0', value=0.5, vary=False), 
..
)
```
does not occur in our examples or documentation.

As predicted and as ignored, this is not a bug.  Closing.

**Closed by newville** 2024-10-14 18:06 UTC
